name: Python API Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests with report
        run: |
          source venv/bin/activate
          pytest --html=reports/report.html --self-contained-html

      - name: Upload test report artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: reports/report.html
